server {
    listen       80;
    server_name  localhost;

    # These prevent Nginx from stripping the 3000 port during redirects
    absolute_redirect off;

    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        # Force reload to stay on index.html
        try_files $uri $uri/ /index.html;
    }
}