name: React Build and Deploy

on:
  schedule:
    # 20:30 UTC is 02:00 IST. The '0' for day represents Sunday.
    - cron: '30 20 * * 0'
  workflow_dispatch: # Allows you to still run it manually for testing

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Custom Branch
        uses: actions/checkout@v4
        with:
          ref: 'release' 

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm install

      - name: Build Project
        run: npm run build

      - name: Deploy to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "build/*"
          target: "/var/www/html"
          strip_components: 1 # Removes the 'build/' folder prefix so files land directly in /html

      - name: Execute Remote SSH Commands
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Update both API and Auth URLs in one go
            sed -i -e 's|WWW_URL_PLACEHOLDER|www.mastercrafters.in|g' \
                   -e 's|URL_PLACEHOLDER|mastercrafters.in|g' \
                   /var/www/html/vite.config.js
            
            sudo systemctl restart nginx

